/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/JRCPEjttPmu
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Switch } from "@/components/ui/switch"
import { Button } from "@/components/ui/button"

export function AddQuestionForSurvey() {
  return (
    <Card className="w-full max-w-2xl">
      <CardHeader>
        <CardTitle>Add New Question</CardTitle>
        <CardDescription>Create a new question for your survey.</CardDescription>
      </CardHeader>
      <CardContent className="grid gap-6">
        <div className="grid grid-cols-2 items-center gap-4">
          <Label htmlFor="title" className="text-right">
            Question Title
          </Label>
          <Input id="title" placeholder="Enter question title" />
        </div>
        <div className="grid grid-cols-2 items-center gap-4">
          <Label htmlFor="multiple-choice" className="text-right">
            Multiple Choice
          </Label>
          <div className="flex items-center gap-2">
            <Switch id="multiple-choice" aria-label="Multiple Choice" />
            <span className="text-sm font-medium">Allow multiple answers</span>
          </div>
        </div>
        <div className="grid gap-4">
          <div className="grid grid-cols-2 items-center gap-4">
            <Label htmlFor="options" className="text-right">
              Options
            </Label>
            <div className="flex flex-col gap-2">
              <div className="flex items-center gap-2">
                <Input id="option-1" placeholder="Option 1" />
                <Button variant="ghost" size="sm">
                  <PlusIcon className="h-4 w-4" />
                </Button>
              </div>
              <div className="flex items-center gap-2">
                <Input id="option-2" placeholder="Option 2" />
                <Button variant="ghost" size="sm">
                  <PlusIcon className="h-4 w-4" />
                </Button>
              </div>
            </div>
          </div>
        </div>
      </CardContent>
      <CardFooter className="flex justify-end">
        <Button>Add Question</Button>
      </CardFooter>
    </Card>
  )
}

function PlusIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function XIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
