/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/dkheCyZ3Hqi
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState, useEffect } from "react"
import { Button } from "./ui/button"
import { ArrowRight, Facebook } from "lucide-react"
import { InstagramLogoIcon, TwitterLogoIcon } from "@radix-ui/react-icons"
import Image from "next/image"
import Link from "next/link"

export function AutoTriggerTabs() {
  const [activeTab, setActiveTab] = useState(0)
  useEffect(() => {
    const interval = setInterval(() => {
      setActiveTab((prevTab) => (prevTab + 1) % 3)
    }, 5000)
    return () => clearInterval(interval)
  }, [])
  return (
    <div className="container mx-auto min-h-screen py-20">
      <div className="flex flex-col gap-5 max-w-3xl mr-auto">
        <h2 className="text-[purple] font-bold text-2xl">Center of Innovation</h2>
        <h1 className="text-4xl font-bold">Driving Innovation in Medical Laboratory Science</h1>
        <p>
Recognizing the rapidly evolving landscape of laboratory technology, the research team is dedicated to empowering researchers, professionals,
         and students to embrace a pioneering mindset and explore creative solutions to address the challenges they face.
          </p>
          <Button className="w-fit rounded-3xl">
            Explore the blog<ArrowRight className="h-3 w-3"/>
          </Button>
      </div>
      <div className="p-6">
        {activeTab === 0 && (
          <div className="grid md:grid-cols-2 gap-5">
            <div className="grid grid-cols-1 gap-2">
              <div>
                <h2 className="font-bold text-2xl">Portable Diagnostics</h2>
                <p className="text-gray-500 max-w-md">
                New portable device detects diseases in Malawi using finger prick test. 
                </p>
              </div>
              <div>
                <h2 className="font-bold text-2xl">Plant-based Antimicrobials</h2>
                <p className="text-gray-500 max-w-md">
                KUHeSMEDLAB researchers are exploring local plants to fight antibiotic resistance. They are looking for natural antibacterials using traditional knowledge and modern science.
                </p>
              </div>
              <div>
                <h2 className="font-bold text-2xl">Collaborative Innovation</h2>
                <p className="text-gray-500 max-w-md">
                Sharing knowledge within KUHeSMEDLAB fuels innovation. Researchers tackle challenges together, finding creative solutions to improve healthcare.
                </p>
              </div>
            </div>
            <div className="relative  md:h-[70vh shadow-2xl rounded-2xl">
              <div className="absolute inset-0 bg-gradient-to-t from-[red] to-transparent opacity-60 shadow-3xl flex flex-col justify-end gap-1 p-5 rounded-2xl" />
              <div className="absolute bottom-0 left-0 right-0 p-6 text-white">
                <p className="text-white font-bold md:text-xl">Scientists say they can cut HIV out of cells</p>
                <Link className="text-white text-xs flex items-center" href={'#'}>Read the article <ArrowRight className="h-4 w-4" /></Link>
              </div>
              <img src="https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" className="w-full rounded-2xl" alt="this is img" />
            </div>
            
          </div>
        )}
        {activeTab === 1 && (
          <div className="grid md:grid-cols-2 gap-5">
          <div className="grid grid-cols-1 gap-2">
            <div>
              <h2 className="font-bold text-2xl">Traditional Knowledge</h2>
              <p className="text-gray-500 max-w-md">Researchers explore natural plant extracts to combat antibiotic resistance.
Locally sourced medicinal plants hold promise for alternative treatments.</p>
            </div>
            <div>
              <h2 className="font-bold text-2xl">Blending Tradition and Science</h2>
              <p className="text-gray-500 max-w-md">Traditional knowledge + modern science = effective compounds.
Malawis local plants show antibacterial activity.</p>
            </div>
            <div>
              <h2 className="font-bold text-2xl">Addressing Antibiotic Resistance</h2>
              <p className="text-gray-500 max-w-md">
              Plant-based antimicrobials combat antibiotic resistance.
KUHeSMEDLAB develops local solutions to improve Malawis healthcare.
              </p>
            </div>
          </div>
          <div className="relative  md:h-[70vh shadow-2xl rounded-2xl">
              <div className="absolute inset-0 bg-gradient-to-t from-[blue] to-transparent opacity-60 shadow-3xl flex flex-col justify-end gap-1 p-5 rounded-2xl" />
              <div className="absolute bottom-0 left-0 right-0 p-6 text-white">
                <p className="text-white font-bold md:text-xl">Using traditional methods to fight antibiotics resistance</p>
                <Link className="text-white text-xs flex items-center" href={'#'}>Read the article <ArrowRight className="h-4 w-4" /></Link>
              </div>
            <img src="https://images.unsplash.com/photo-1583911860331-9fd6ce32c78f?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" className="w-full rounded-2xl" alt="this is img" />
          </div>
          
        </div>
        )}
        {activeTab === 2 && (
          <div className="grid md:grid-cols-2 gap-5">
          <div className="grid grid-cols-1 gap-2">
            <div>
              <h2 className="font-bold text-2xl">Empowering the Next Generation</h2>
              <p className="text-gray-500 max-w-md">
              KUHeSMEDLAB fosters innovation beyond the lab.
Educational opportunities for future medical laboratory scientists.
              </p>
            </div>
            <div>
              <h2 className="font-bold text-2xl">Inspiring and Empowering</h2>
              <p className="text-gray-500 max-w-md">
              Workshops, mentorship, and research projects empower students and early-career professionals.
              </p>
            </div>
            <div>
              <h2 className="font-bold text-2xl">Cultivating a Pioneering Mindset</h2>
              <p className="text-gray-500 max-w-md">
              Investing in the next generation of scientists.
Empowering innovation and problem-solving in Malawi.
              </p>
            </div>
          </div>
          <div className="relative  md:h-[70vh shadow-2xl rounded-2xl">
              <div className="absolute inset-0 bg-gradient-to-t from-[yellow] to-transparent opacity-60 shadow-3xl flex flex-col justify-end gap-1 p-5 rounded-2xl" />
              <div className="absolute bottom-0 left-0 right-0 p-6 text-white">
                <p className="text-white font-bold md:text-xl">See how different sectors are uniting using this platform to Educational opportunities for future medical laboratory scientists.</p>
                <Link className="text-white text-xs flex items-center" href={'#'}>Read the article <ArrowRight className="h-4 w-4" /></Link>
              </div>
            <img src="https://images.unsplash.com/photo-1581594549595-35f6edc7b762?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" className="w-full rounded-2xl" alt="this is img" />
          </div>
          
        </div>
        )}
      </div>
      <div className="grid grid-cols-3 w-full items-center justify-center border-t border-muted">
        <button
          className={`flex items-center justify-center gap-2 px-4 py-10 text-sm font-medium transition-colors ${
            activeTab === 0 ? "text-primary border-t-2 border-primary" : "text-muted-foreground hover:text-primary"
          }`}
          onClick={() => setActiveTab(0)}
        >
          <Image src={'/diagnosis.png'} alt="diagnosis" className="h-12 w-12 font-bold hidden md:block" height={50} width={50}/>
          
          <p className="hidden md:block">DIAGNOSIS</p>
        </button>
        <button
          className={`flex items-center justify-center gap-2 px-4 py-10 text-sm font-medium transition-colors ${
            activeTab === 1 ? "text-primary border-t-2 border-primary" : "text-muted-foreground hover:text-primary"
          }`}
          onClick={() => setActiveTab(1)}
        >
          <Image src={'/traditional-medicine.png'} alt="diagnosis" className="h-12 w-12 font-bold hidden md:block" height={50} width={50}/>
          
          <p className="hidden md:block">TRADITION</p>
        </button>
        <button
          className={`flex items-center justify-center gap-2 px-4 py-10 text-sm font-medium transition-colors ${
            activeTab === 2 ? "text-primary border-t-2 border-primary" : "text-muted-foreground hover:text-primary"
          }`}
          onClick={() => setActiveTab(2)}
        >

          <Image src={'/nurturing.png'} alt="diagnosis" className="h-12 w-12 font-bold hidden md:block" height={50} width={50}/>
          <p className="hidden md:block">EMPOWER</p>
          
        </button>
      </div>
      
    </div>
  )
}
