/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ZCq3SmDvHl1
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function CreateFirstWorkspace() {
  return (
    <section className="w-full rounded-3xl bg-primary py-12 md:py-24 lg:py-32">
      <div className="container grid items-center gap-6 px-4 md:px-6">
        <div className="space-y-3">
          <h2 className="text-3xl font-bold tracking-tighter text-primary-foreground md:text-4xl/tight">
            Set Up Your Research Workspace
          </h2>
          <p className="max-w-[600px] text-primary-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
            Get started by creating a new research workspace to organize your research projects, data, and insights.
          </p>
        </div>
       
      </div>
    </section>
  )
}
