/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/6XxyAdsiGxa
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { ArrowRight } from "lucide-react";
import Link from "next/link";
import { Badge } from "./ui/badge";

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function DashboardTraining() {
  return (
    <div className=" container space-y-10 my-20 mx-auto">
      <h2 className="text-3xl font-sans ">Top Discoveries</h2>
      <div className="grid md:grid-cols-2 gap-4 " >
      <div className="relative overflow-hidden rounded-3xl shadow-lg group hover:shadow-xl">
        <img
          src="https://dbdmedical.com/wp-content/uploads/2023/02/black-history-health-large.jpg"
          alt="Card 1"
          // width={800}
          // height={400}
          className="object-cover w-full max-h-full transition-transform duration-300 ease-in-out group-hover:scale-105"
        />
        <div className="absolute inset-0 bg-gradient-to-t from-white to-transparent" />
        <div className="absolute inset-0 flex flex-col justify-between space-y-10 p-6 ">
          <Badge className='bg-gradient-to-r w-fit from-blue-200 to-purple-300 text-xs text-gray-500'>
              Medical
          </Badge>
          <div>
            <h3 className="text-2xl mb-2">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Totam, minima!</h3>
            <div>
              <Link href={'#'}>
                <ArrowRight className="h-4 w-4" />
              </Link>
            </div>
            
          </div>
          
          
        </div>
      </div>
      <div className="grid md:grid-rows-2 gap-4">
        <div className="relative overflow-hidden rounded-3xl shadow-lg group hover:shadow-xl">
          <img
            src="https://dbdmedical.com/wp-content/uploads/2023/02/black-history-health-large.jpg"
            alt="Card 2"
            width={400}
            height={200}
            className="object-cover w-full h-full md:max-h-[50vh] transition-transform duration-300 ease-in-out group-hover:scale-105"
          />
          <div className="absolute inset-0 bg-gradient-to-t from-white to-transparent" />
          <div className="absolute inset-0 flex flex-col justify-between space-y-10 p-6 ">
          <Badge className='bg-gradient-to-r w-fit from-blue-200 to-purple-300 text-xs text-gray-500'>
              Medical
          </Badge>
          <div>
            <h3 className="text-2xl mb-2">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Totam, minima!</h3>
            <div>
              <Link href={'#'}>
                <ArrowRight className="h-4 w-4" />
              </Link>
            </div>
            
          </div>
          
          
        </div>
        </div>
        <div className="relative overflow-hidden rounded-3xl shadow-lg group hover:shadow-xl">
          <img
            src="https://dbdmedical.com/wp-content/uploads/2023/02/black-history-health-large.jpg"
            alt="Card 3"
            width={400}
            height={200}
            className="object-cover md:max-h-[50vh] w-full transition-transform duration-300 ease-in-out group-hover:scale-105"
          />
          <div className="absolute inset-0 bg-gradient-to-t from-white to-transparent" />
          <div className="absolute inset-0 flex flex-col justify-between space-y-10 p-6 ">
          <Badge className='bg-gradient-to-r w-fit from-blue-200 to-purple-300 text-xs text-gray-500'>
              Medical
          </Badge>
          <div>
            <h3 className="text-2xl mb-2">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Totam, minima!</h3>
            <div>
              <Link href={'#'}>
                <ArrowRight className="h-4 w-4" />
              </Link>
            </div>
            
          </div>
          
          
        </div>
        </div>
      </div>
      </div>
      
    </div>
  )
}
