/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/1WxWWXqNwT7
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function EventsGrid() {
  return (
    <div className="relative">
      <div className="absolute inset-x-0 top-40 bottom-0 h-[30rem] bg-[#2a2e7c] -skew-y-12 origin-top-left" /> 
        <div className="grid md:grid-cols-3 md:grid-rows-2 gap-6 container mx-auto p-6 sm:p-10">
        <div className="col-span-1 bg-white border-b-8 border-b-blue-600 row-span-1 bg-background rounded-lg shadow-lg overflow-hidden transform rotate-6">
          <img
            src="https://images.unsplash.com/photo-1500989145603-8e7ef71d639e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1655&q=80"
            alt="Annual Medical Conference"
            width={400}
            height={300}
            className="w-full h-48 object-cover"
          />
          <div className="p-6">
            <h3 className="text-lg font-semibold mb-2">Annual Medical Conference</h3>
            <p className="text-sm text-muted-foreground mb-4">June 15-18, 2024</p>
            <p className="text-sm">
              Join us for the annual medical conference, featuring the latest advancements in healthcare technology and
              research.
            </p>
          </div>
        </div>
        <div className="col-span-1 row-span-1 bg-white border-b-8 border-b-blue-600 rounded-lg shadow-lg overflow-hidden transform -rotate-6">
          <img
            src="https://images.unsplash.com/photo-1500989145603-8e7ef71d639e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1655&q=80"
            alt="Diagnostic Imaging Workshop"
            width={400}
            height={300}
            className="w-full h-48 object-cover"
          />
          <div className="p-6">
            <h3 className="text-lg font-semibold mb-2">Diagnostic Imaging Workshop</h3>
            <p className="text-sm text-muted-foreground mb-4">September 7-9, 2024</p>
            <p className="text-sm">Explore the latest techniques in diagnostic imaging at our hands-on workshop.</p>
          </div>
        </div>
        <div className="col-span-1 row-span-1 bg-white border-b-8 border-b-blue-600 rounded-lg shadow-lg overflow-hidden transform rotate-6">
          <img
            src="https://images.unsplash.com/photo-1500989145603-8e7ef71d639e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1655&q=80"
            alt="Precision Medicine Symposium"
            width={400}
            height={300}
            className="w-full h-48 object-cover"
          />
          <div className="p-6">
            <h3 className="text-lg font-semibold mb-2">Precision Medicine Symposium</h3>
            <p className="text-sm text-muted-foreground mb-4">November 12-14, 2024</p>
            <p className="text-sm">Discover the latest advancements in precision medicine and personalized healthcare.</p>
          </div>
        </div>
        <div className="col-span-1 row-span-1 bg-white border-b-8 border-b-blue-600 rounded-lg shadow-lg overflow-hidden transform -rotate-6">
          <img
            src="https://images.unsplash.com/photo-1500989145603-8e7ef71d639e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1655&q=80"
            alt="Genomics Research Forum"
            width={400}
            height={300}
            className="w-full h-48 object-cover"
          />
          <div className="p-6">
            <h3 className="text-lg font-semibold mb-2">Genomics Research Forum</h3>
            <p className="text-sm text-muted-foreground mb-4">February 20-22, 2025</p>
            <p className="text-sm">Join leading experts in the field of genomics for this informative research forum.</p>
          </div>
        </div>
        <div className="col-span-1 row-span-1 bg-white border-b-8 border-b-blue-600 rounded-lg shadow-lg overflow-hidden transform rotate-6">
          <img
            src="https://images.unsplash.com/photo-1500989145603-8e7ef71d639e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1655&q=80"
            alt="Biomedical Innovation Showcase"
            width={400}
            height={300}
            className="w-full h-48 object-cover"
          />
          <div className="p-6">
            <h3 className="text-lg font-semibold mb-2">Biomedical Innovation Showcase</h3>
            <p className="text-sm text-muted-foreground mb-4">April 5-7, 2025</p>
            <p className="text-sm">Explore the latest innovations in biomedical technology at our annual showcase.</p>
          </div>
        </div>
        <div className="col-span-1 row-span-1 bg-white border-b-8 border-b-blue-600 rounded-lg shadow-lg overflow-hidden transform -rotate-6">
          <img
            src="https://images.unsplash.com/photo-1500989145603-8e7ef71d639e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1655&q=80"
            alt="Clinical Trials Symposium"
            width={400}
            height={300}
            className="w-full h-48 object-cover"
          />
          <div className="p-6">
            <h3 className="text-lg font-semibold mb-2">Clinical Trials Symposium</h3>
            <p className="text-sm text-muted-foreground mb-4">July 1-3, 2025</p>
            <p className="text-sm">
              Join us for an in-depth look at the latest developments in clinical trials and patient-centered research.
            </p>
          </div>
        </div>
      </div>
    </div>

  )
}
