/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/MrlXEAXwTV5
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from "@/components/ui/collapsible"
import { faq } from "@/lib/faq"
import { ChevronDownIcon, FileQuestionIcon } from "lucide-react"

type Faq = {
  question:string,
  answer:string
}

export function Faq() {
  return (
    <section id="faq" className="w-full py-24 bg-gray-100">
      <div className="container mx-auto">
        <div className="">
          <div className="text-center">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Frequently Asked Questions</h2>
            <p className="mt-2 text-muted-foreground md:text-xl my-5">
              Get answers to the most common questions about our medical lab research program.
            </p>
          </div>
          <div className="space-y-4 text-xs md:text-lg">
            {faq.map((fa:Faq, index)=>(
              <Collapsible key={index}>
              <CollapsibleTrigger className="w-full flex items-center justify-between rounded-lg bg-background px-6 py-4 transition-colors hover:bg-accent hover:text-accent-foreground focus:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2">
                <div className="flex items-center gap-4">
                  <div className="rounded-full bg-primary p-2 text-primary-foreground">
                    <FileQuestionIcon className="h-5 w-5" />
                  </div>
                  <h3 className="font-medium">{fa.question}</h3>
                </div>
                <ChevronDownIcon className="h-5 w-5 transition-transform [&[data-state=open]]:rotate-180" />
              </CollapsibleTrigger>
              <CollapsibleContent className="px-6 pt-4 pb-6 text-muted-foreground">
                <p>
                  {fa.answer}
                </p>
              </CollapsibleContent>
            </Collapsible>
            ))}
            
          </div>
        </div>
      </div>
    </section>
  )
}
