/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Qjoh7Wxz8jn
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"
import { Command, CommandInput, CommandList, CommandEmpty, CommandGroup, CommandItem } from "@/components/ui/command"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { GroupMembers } from "./GroupMembers"
import { IconMailAi } from "@tabler/icons-react"

export function InviteSurvey() {
  return (
    <Card className="w-full bg-white border-none">
      <CardHeader>
        <div className="space-y-1.5">
          <CardTitle>Invite Collaborators</CardTitle>
          <CardDescription>Add collaborators to your event.</CardDescription>
        </div>
      </CardHeader>
      <CardContent>
        {/* <GroupMembers /> */}
        <form className="space-y-4">
          
          <div className="space-y-2 flex gap-2">
            <DropdownMenu>
              <DropdownMenuTrigger className="w-full cursor-pointer relative bg-gradient-to-r from-blue-300 to-purple-400 rounded-md px-2 " asChild>
                  <span className="flex items-center text-white text-xs font-bold justify-between">
                    Add collaborators
                  <ChevronDownIcon className="h-4 w-4" />
                  </span>
                  
              </DropdownMenuTrigger>
              <DropdownMenuContent className="w-full bg-white shadow-2xl shadow-purple-400">
                <DropdownMenuLabel>Collaborators</DropdownMenuLabel>
                <DropdownMenuSeparator />
                <Command>
                  <CommandInput placeholder="Search collaborators..." className="h-9" />
                  <CommandList>
                    <CommandEmpty>No collaborators found.</CommandEmpty>
                    <CommandGroup>
                      <CommandItem>
                        <Avatar className="h-6 w-6 mr-2">
                          <AvatarImage src="/placeholder-user.jpg" />
                          <AvatarFallback>JD</AvatarFallback>
                        </Avatar>
                        John Doe
                      </CommandItem>
                      <CommandItem>
                        <Avatar className="h-6 w-6 mr-2">
                          <AvatarImage src="/placeholder-user.jpg" />
                          <AvatarFallback>JA</AvatarFallback>
                        </Avatar>
                        Jane Appleseed
                      </CommandItem>
                      <CommandItem>
                        <Avatar className="h-6 w-6 mr-2">
                          <AvatarImage src="/placeholder-user.jpg" />
                          <AvatarFallback>SM</AvatarFallback>
                        </Avatar>
                        Sarah Musk
                      </CommandItem>
                      <CommandItem>
                        <Avatar className="h-6 w-6 mr-2">
                          <AvatarImage src="/placeholder-user.jpg" />
                          <AvatarFallback>DW</AvatarFallback>
                        </Avatar>
                        David Wang
                      </CommandItem>
                    </CommandGroup>
                  </CommandList>
                </Command>
              </DropdownMenuContent>
            </DropdownMenu>
            <button className="px-8 py-2  rounded-md relative bg-slate-700 text-white text-sm hover:shadow-2xl hover:shadow-white/[0.1] transition duration-200 border border-slate-600">
            <div className="absolute inset-x-0 h-px w-1/2 mx-auto -top-px shadow-2xl  bg-gradient-to-r from-transparent via-teal-500 to-transparent" />
            <span className="relative flex items-center gap-1 z-20">
              Invite
            </span>
          </button>
          </div>
          
        </form>
      </CardContent>
    </Card>
  )
}

function ChevronDownIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}


function XIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
