/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Qjoh7Wxz8jn
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"
import { Command, CommandInput, CommandList, CommandEmpty, CommandGroup, CommandItem } from "@/components/ui/command"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { GroupMembers } from "./GroupMembers"

export function InviteSurvey() {
  return (
    <Card className="w-full bg-transparent border-none">
      <CardHeader>
        <div className="space-y-1.5">
          <CardTitle>Invite Collaborators</CardTitle>
          <CardDescription>Add collaborators to your event.</CardDescription>
        </div>
      </CardHeader>
      <CardContent>
        <GroupMembers />
        <form className="space-y-4">
          
          <div className="space-y-2">
            <Label htmlFor="collaborators">Collaborators</Label>
            <DropdownMenu>
              <DropdownMenuTrigger className="w-full relative text-sm sm:text-base z-50 border-2 border-green-600 dark:text-white bg-transparent text-black h-full rounded-full focus:outline-none focus:ring-0 pl-4 sm:pl-10 pr-20 " asChild>
                  <span className="flex items-center justify-between">
                    Add collaborators
                  <ChevronDownIcon className="h-4 w-4" />
                  </span>
                  
              </DropdownMenuTrigger>
              <DropdownMenuContent className="w-[300px] bg-background">
                <DropdownMenuLabel>Collaborators</DropdownMenuLabel>
                <DropdownMenuSeparator />
                <Command>
                  <CommandInput placeholder="Search collaborators..." className="h-9" />
                  <CommandList>
                    <CommandEmpty>No collaborators found.</CommandEmpty>
                    <CommandGroup>
                      <CommandItem>
                        <Avatar className="h-6 w-6 mr-2">
                          <AvatarImage src="/placeholder-user.jpg" />
                          <AvatarFallback>JD</AvatarFallback>
                        </Avatar>
                        John Doe
                      </CommandItem>
                      <CommandItem>
                        <Avatar className="h-6 w-6 mr-2">
                          <AvatarImage src="/placeholder-user.jpg" />
                          <AvatarFallback>JA</AvatarFallback>
                        </Avatar>
                        Jane Appleseed
                      </CommandItem>
                      <CommandItem>
                        <Avatar className="h-6 w-6 mr-2">
                          <AvatarImage src="/placeholder-user.jpg" />
                          <AvatarFallback>SM</AvatarFallback>
                        </Avatar>
                        Sarah Musk
                      </CommandItem>
                      <CommandItem>
                        <Avatar className="h-6 w-6 mr-2">
                          <AvatarImage src="/placeholder-user.jpg" />
                          <AvatarFallback>DW</AvatarFallback>
                        </Avatar>
                        David Wang
                      </CommandItem>
                    </CommandGroup>
                  </CommandList>
                </Command>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
          <button className="px-12 w-full py-4 rounded-full bg-[#1ED760] font-bold text-white tracking-widest uppercase transform hover:scale-105 hover:bg-[#21e065] transition-colors duration-200">
            Invite
          </button>
        </form>
      </CardContent>
    </Card>
  )
}

function ChevronDownIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}


function XIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
