/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Nj23XOUPrkD
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { ArrowRight } from "lucide-react";
import { Badge } from "./ui/badge";
import { Input } from "./ui/input";
import { Button } from "./ui/button";
import { BackgroundGradientAnimation } from "./ui/background-gradient-animation";
import Trustedby from "./Trustedby";
import { ArrowRightIcon } from "@radix-ui/react-icons";
import Link from "next/link";

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts

**/

{/* <div className="absolute inset-x-0 top-40 bottom-0 h-[30rem] bg-[#A3CCE5] -skew-y-12 origin-top-left" /> */}
        {/* <div className="absolute inset-x-0 top-40 bottom-0 h-[30rem] bg-[#A3CCE5] skew-y-12 origin-bottom-right" /> */}

export function LandingFirst() {
  return (
    <div className="flex min-h-screen  items-center  w-full">
        <BackgroundGradientAnimation className=" -skew-y-12 origin-top-left" />
        <BackgroundGradientAnimation className=" skew-y-12 origin-bottom-right" />
        <div className="max-w-7xl text-center mx-auto z-10  p-6 md:p-0 ">
          <div className=" space-y-5 mt-20 mx-auto text-gray-100">
          <div className="max-w-3xl mx-auto text-center mb-5 lg:mb-5 overflow-hidden tracking-[3px] text-xs md:px-5 md:py-2 uppercase bg-black bg-opacity-10 text-white rounded-full px-4 py-2">
            <span className="md:flex items-center gap-2 ">Explore how ai is advancing medical reseach in todays world of tech <ArrowRightIcon className="hidden md:block" /></span>
            </div>
            <h1 className="text-6xl lg:text-8xl font-bold text-black text-opacity-75 ">Advancing Medical Laboratory Science </h1>
            <p className="md:text-xl pb-10 max-w-4xl mx-auto text-balance">Empowering medical laboratory profession to drive innovation, collaboration,
               and excellence in healthcare using AI and technology
                through research, discovery, and data-driven solutions.
             </p>
             
          </div>
          <div className="flex flex-col md:flex-row gap-2 items-center justify-center">
          <Link href={'/signin'} className="bg-slate-800 no-underline group cursor-pointer relative shadow-2xl shadow-zinc-900 rounded-full p-px text-xs font-semibold leading-6  text-white inline-block">
              <span className="absolute inset-0 overflow-hidden rounded-full">
                <span className="absolute inset-0 rounded-full bg-[image:radial-gradient(75%_100%_at_50%_0%,rgba(56,189,248,0.6)_0%,rgba(56,189,248,0)_75%)] opacity-0 transition-opacity duration-500 group-hover:opacity-100" />
              </span>
              <div className="relative flex space-x-2 items-center z-10 rounded-full bg-zinc-950 py-0.5 px-4 ring-1 ring-white/10 ">
                <span>
                  Get Started
                </span>
                <svg
                  fill="none"
                  height="16"
                  viewBox="0 0 24 24"
                  width="16"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M10.75 8.75L14.25 12L10.75 15.25"
                    stroke="currentColor"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="1.5"
                  />
                </svg>
              </div>
              <span className="absolute -bottom-0 left-[1.125rem] h-px w-[calc(100%-2.25rem)] bg-gradient-to-r from-emerald-400/0 via-emerald-400/90 to-emerald-400/0 transition-opacity duration-500 group-hover:opacity-40" />
            </Link>

              <Link href={'/signin'} className="px-8 py-2 text-gray-500 flex items-center gap-2  bg-transparent rounded-[6px]  relative group transition duration-20 hover:bg-transparent">
                Learn more 
                <svg
                  fill="none"
                  height="16"
                  viewBox="0 0 24 24"
                  width="16"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M10.75 8.75L14.25 12L10.75 15.25"
                    stroke="currentColor"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="1.5"
                  />
                </svg>
              </Link>
           
          </div>
          <div>
            <div className="p-6 shadow-2xl shadow-gray-200 rounded-lg bg-opacity-20 bg-white">
              <img src="https://scontent.fblz1-1.fna.fbcdn.net/v/t39.30808-6/455265995_921894826636112_1523723343655404444_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=833d8c&_nc_eui2=AeERLiR-SlN6FYioRJCDK-xcq1DtVCVakYCrUO1UJVqRgIx5NPPUwhwKVSto1_MHmEJHdN2TUwNbvc2GzVC1xEjy&_nc_ohc=7eUHtHegNUsQ7kNvgFCz7cy&_nc_pt=5&_nc_zt=23&_nc_ht=scontent.fblz1-1.fna&oh=00_AYAuRQPBSBtr-_XL_q5u1ARtvLGE9OkjoTJ-eEAYjrQIdw&oe=66C233E6" className="w-full h-full rounded-lg" />
            </div>
          </div>
          <Trustedby />
        </div>
      </div>
    
  )
}
