/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/AaX1bpgG012
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

"use client"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { Button } from "@/components/ui/button"
import { CartesianGrid, XAxis, Line, LineChart, Bar, BarChart } from "recharts"
import { ChartTooltipContent, ChartTooltip, ChartContainer } from "@/components/ui/chart"

export function Profilesec() {
  return (
    <div className="grid grid-cols-2 gap-5 mx-5 ">
      <aside className=" p-10 rounded-3xl bg-white shadow">
        <div className="flex items-center space-x-4">
          <div className="h-5 w-5 rounded-full bg-purple-400" />
          <div>
            <h2 className="text-xl font-bold">Sara Johansen</h2>
            <p className="text-sm text-black">36 years old, Female</p>
          </div>
          
        </div>
        <div className="mt-6 bg-green-50 rounded-3xl p-6">
          <h3 className="text-lg font-semibold">Glucose</h3>
          <LinechartChart className="aspect-[4/3]" />
        </div>
        <div className="mt-6">
          <h3 className="text-lg font-semibold">Weight</h3>
          <BarchartChart className="w-full aspect-[4/3]" />
        </div>
        <div className="mt-6 grid grid-cols-3 gap-4 text-center">
          <div>
            <p className="text-sm font-semibold">Heart Rate</p>
            <p className="text-lg font-bold text-red-500">184 bpm</p>
          </div>
          <div>
            <p className="text-sm font-semibold">Temperature</p>
            <p className="text-lg font-bold text-red-500">36.6°C</p>
          </div>
          <div>
            <p className="text-sm font-semibold">Blood Pressure</p>
            <p className="text-lg font-bold text-blue-500">140/90 mm/hg</p>
          </div>
        </div>
      </aside>
      <main className="w-full bg-white h-fit shadow rounded-3xl p-6">
        <Tabs className="bg-blue-50 m-6 rounded-3xl p-6" defaultValue="overview">
          <TabsList className="flex bg-white rounded-2xl space-x-4">
            <TabsTrigger value="bio">BIO</TabsTrigger>
            <TabsTrigger value="overview">OVERVIEW</TabsTrigger>
            <TabsTrigger value="calendar">CALENDAR</TabsTrigger>
            <TabsTrigger value="documents">DOCUMENTS</TabsTrigger>
          </TabsList>
          <TabsContent value="overview">
            <div className="mt-6">
              <h3 className="text-lg font-semibold">Diagnosis</h3>
              <p className="text-sm text-black">
                Patient reports she has never had his teeth cleaned and is anxious about great dental work. The patient
                is not under the care. Patient reports she has never had his teeth cleaned and is anxious about great
                dental work. The patient is not under the...
                <a href="#" className="text-blue-500">
                  more
                </a>
              </p>
            </div>
            <div className="mt-6">
              <h3 className="text-lg font-semibold">Symptoms</h3>
              <p className="text-sm text-black">
                Patient reports she has never had his teeth cleaned and is anxious about great dental work. The patient
                is not under the care. Patient reports she has never had his teeth cleaned and is...
                <a href="#" className="text-blue-500">
                  more
                </a>
              </p>
            </div>
            <div className="mt-6">
              <h3 className="text-lg font-semibold">Reseach files</h3>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Doctor</TableHead>
                    <TableHead>Date</TableHead>
                    <TableHead>Time</TableHead>
                    <TableHead>Status</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow>
                    <TableCell className="flex items-center space-x-2">
                      <Avatar>
                        <AvatarImage src="/placeholder-user.jpg" />
                        <AvatarFallback>JO</AvatarFallback>
                      </Avatar>
                      <div>
                        <p className="font-medium">Justin Olson</p>
                        <p className="text-sm text-black">Orthodontics</p>
                      </div>
                    </TableCell>
                    <TableCell>Aug 21, 2018</TableCell>
                    <TableCell>10:00 am</TableCell>
                    <TableCell>
                      <CheckIcon className="w-5 h-5 text-green-500" />
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="flex items-center space-x-2">
                      <Avatar>
                        <AvatarImage src="/placeholder-user.jpg" />
                        <AvatarFallback>FJ</AvatarFallback>
                      </Avatar>
                      <div>
                        <p className="font-medium">Franklin Johnson</p>
                        <p className="text-sm text-black">Surgeon</p>
                      </div>
                    </TableCell>
                    <TableCell>Aug 21, 2018</TableCell>
                    <TableCell>10:30 am</TableCell>
                    <TableCell>
                      <CheckIcon className="w-5 h-5 text-green-500" />
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="flex items-center space-x-2">
                      <Avatar>
                        <AvatarImage src="/placeholder-user.jpg" />
                        <AvatarFallback>CM</AvatarFallback>
                      </Avatar>
                      <div>
                        <p className="font-medium">Curtis Milner</p>
                        <p className="text-sm text-black">Dentist</p>
                      </div>
                    </TableCell>
                    <TableCell>Aug 21, 2018</TableCell>
                    <TableCell>11:00 am</TableCell>
                    <TableCell>
                      <ClockIcon className="w-5 h-5 text-red-500" />
                    </TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </div>
            <div className="mt-6">
              <h3 className="text-lg font-semibold">Attachments</h3>
              <div className="flex space-x-4">
                <Button variant="outline" className="flex items-center space-x-2">
                  <FileIcon className="w-5 h-5" />
                  <span>Supplemental Info</span>
                  <span className="text-sm text-black">IMG, 10/03/2017</span>
                </Button>
                <Button variant="outline" className="flex items-center space-x-2">
                  <FileIcon className="w-5 h-5" />
                  <span>Prev Analysis</span>
                  <span className="text-sm text-black">DOC, 05/07/2017</span>
                </Button>
              </div>
            </div>
          </TabsContent>
        </Tabs>
      </main>
      <div className="fixed bottom-6 right-6 flex space-x-4">
        <Button className="rounded-full p-4">
          <PlusIcon className="w-6 h-6 text-white" />
        </Button>
        <Button className="rounded-full p-4">
          <MessageCircleIcon className="w-6 h-6 text-white" />
        </Button>
      </div>
    </div>
  )
}

function BarchartChart(props:any) {
  return (
    <div {...props}>
      <ChartContainer
        config={{
          desktop: {
            label: "Desktop",
            color: "hsl(var(--chart-1))",
          },
        }}
        className="min-h-[300px]"
      >
        <BarChart
          accessibilityLayer
          data={[
            { month: "January", desktop: 186 },
            { month: "February", desktop: 305 },
            { month: "March", desktop: 237 },
            { month: "April", desktop: 73 },
            { month: "May", desktop: 209 },
            { month: "June", desktop: 214 },
          ]}
        >
          <CartesianGrid vertical={false} />
          <XAxis
            dataKey="month"
            tickLine={false}
            tickMargin={10}
            axisLine={false}
            tickFormatter={(value) => value.slice(0, 3)}
          />
          <ChartTooltip cursor={false} content={<ChartTooltipContent hideLabel />} />
          <Bar dataKey="desktop" fill="var(--color-desktop)" radius={8} />
        </BarChart>
      </ChartContainer>
    </div>
  )
}


function CheckIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}


function ClockIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>
  )
}


function FileIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
    </svg>
  )
}


function LinechartChart(props:any) {
  return (
    <div {...props}>
      <ChartContainer
        config={{
          desktop: {
            label: "Desktop",
            color: "hsl(var(--chart-1))",
          },
        }}
      >
        <LineChart
          accessibilityLayer
          data={[
            { month: "January", desktop: 186 },
            { month: "February", desktop: 305 },
            { month: "March", desktop: 237 },
            { month: "April", desktop: 73 },
            { month: "May", desktop: 209 },
            { month: "June", desktop: 214 },
          ]}
          margin={{
            left: 12,
            right: 12,
          }}
        >
          <CartesianGrid vertical={false} />
          <XAxis
            dataKey="month"
            tickLine={false}
            axisLine={false}
            tickMargin={8}
            tickFormatter={(value) => value.slice(0, 3)}
          />
          <ChartTooltip cursor={false} content={<ChartTooltipContent hideLabel />} />
          <Line dataKey="desktop" type="natural" stroke="var(--color-desktop)" strokeWidth={2} dot={false} />
        </LineChart>
      </ChartContainer>
    </div>
  )
}


function LocateIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="2" x2="5" y1="12" y2="12" />
      <line x1="19" x2="22" y1="12" y2="12" />
      <line x1="12" x2="12" y1="2" y2="5" />
      <line x1="12" x2="12" y1="19" y2="22" />
      <circle cx="12" cy="12" r="7" />
    </svg>
  )
}


function MessageCircleIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z" />
    </svg>
  )
}


function PhoneIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>
  )
}


function PlusIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function XIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
