/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/mwt5gUXbL4z
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { Checkbox } from "@/components/ui/checkbox"

export function RegisterForm() {
  return (
      <Card className="w-full shadow md:px-8">
        <CardHeader className="space-y-2 text-center">
          <CardTitle className="text-2xl font-bold my-10 mx-w-sm">Create your KuhesMedLab account today.</CardTitle>
          <CardDescription></CardDescription>
        </CardHeader>
        <CardContent className="space-y-8">
          <div className="grid gap-2">
            <Label htmlFor="name">Full Name</Label>
            <Input id="name" type="text" className="rounded-md" />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="email">Email</Label>
            <Input id="email" type="email" className="rounded-md" />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="country">Country</Label>
            <Select >
              <SelectTrigger>
                <SelectValue placeholder="Select country" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="us">Malawi</SelectItem>
                <SelectItem value="ca">Canada</SelectItem>
                <SelectItem value="uk">United Kingdom</SelectItem>
                <SelectItem value="au">Australia</SelectItem>
                <SelectItem value="de">Germany</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="grid gap-2">
            <Label htmlFor="password">Password</Label>
            <Input id="password" type="password" className="rounded-md" />
          </div>
          <div className="flex gap-2 items-start">
            <Checkbox />
            <p className="text-xs">By registering it means you have accept our terms and conditions
               </p>
          </div>
        </CardContent>
        <CardFooter className="flex flex-col gap-5">
          <Button className="w-full rounded-md">Register</Button>
          <p className="text-xs">Already have an account ? <Link className="text-[#2a2e7c] underline" href={'/signin'} >signin</Link></p>
        </CardFooter>
      </Card>
  )
}
