/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Nj23XOUPrkD
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { ArrowRight, Star } from "lucide-react";
import { Badge } from "./ui/badge";
import { Input } from "./ui/input";
import { Button } from "./ui/button";
import { BackgroundGradientAnimation } from "./ui/background-gradient-animation";
import Trustedby from "./Trustedby";

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Register() {
  return (
      <div className="relative h-screen w-full">
        <div className="absolute inset-x-0  bottom-0 h-[30rem] bg-[#A3CCE5] -skew-y-12 origin-top-left" />
        <div className="absolute inset-x-0  bottom-0 h-[30rem] bg-[#A3CCE5] origin-bottom-right" />
        <div className="relative max-w-7xl mx-auto z-10 md:grid grid-cols-2 p-6 gap-6">
          <div className=" max-w-lg flex flex-col gap-4 text-start ">
            <h2 className="font-extrabold">Kuhesmedlab</h2>
            <div className="flex gap-2 items-start">
                <Star className="h-4 w-4" />
                <div>
                    <h2 className="font-bold mb-2">Get started quickly</h2>
                    <p className="text-xs">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati, possimus.</p>
                </div>
            </div>
            <div className="flex gap-2 items-start">
                <Star className="h-4 w-4" />
                <div>
                    <h2 className="font-bold mb-2">Get started quickly</h2>
                    <p className="text-xs">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati, possimus.</p>
                </div>
            </div>
          </div>
          <div></div>
        </div>
      </div>
    
  )
}
