/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/X1e8Gyt0VJ2
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Badge } from "./ui/badge"

export function Researchsec() {
  return (
    <section id="published" className="w-full py-12 md:py-24 lg:py-32">
      <div className="relative container px-4 md:px-6">
      <div
            aria-hidden='true'
            className='pointer-events-none absolute inset-x-0 -top-40 -z-10 transform-gpu overflow-hidden blur-3xl sm:-top-80'>
            <div
              style={{
                clipPath:
                  'polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)',
              }}
              className='relative left-[calc(50%-11rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 rotate-[30deg] bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30 sm:left-[calc(50%-30rem)] sm:w-[72.1875rem]'
            />
          </div>
      <Badge className='text-gray-100 bg-gradient-to-r from-blue-400 to-purple-500 uppercase'>Recent Published Research</Badge>

<div className=" py-10 dark:bg-gray-700 transition duration-500">
  <div className="relative lg:mx-auto mx-2">
    <div className="breadcrumb text-sm text-gray-900 font-normal flex flex-row space-x-2 my-2 dark:text-gray-50">
      <a href="#">The publications are verified and approved before published</a>
      <a href="#">✌️ </a>
    </div>
    {/* <div className="relative blog-header-image rounded-lg shadow-lg overflow-hidden h-48 object-cover">
      <img src="https://www.shutterstock.com/image-vector/vector-illustration-approved-label-flag-600nw-1506750614.jpg" className="object-cover object-center w-full" alt="headerImage" />
    </div> */}
    <span aria-label="emoji" className="absolute left-1/2 -bottom-5 text-6xl">🍁</span>
  </div>
  <div className="">
    <h1 className="text-center font-bold text-gray-600 text-4xl mt-10 dark:text-gray-50">The recent published research</h1>

    <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mt-20">
      <div className="blog-card flex flex-col items-center md:items-start cursor-pointer">
        <div className="img-container rounded-md overflow-hidden w-3/4 sm:w-1/2 mx-auto md:w-full lg:h-48">
          <img src="https://media.istockphoto.com/id/1465316262/photo/businessman-inspecting-paperwork-document-of-business-data-analysis-working-management-report.webp?b=1&s=170667a&w=0&k=20&c=L6xi5VJG0gr3a40-i35k8XWcmglc5hlgYP-lSqdEd9s=" className="object-cover" alt="headerImage" />
        </div>
        <h1 className="mt-4 text-xl font-semibold dark:text-gray-50">Investigating the Impact of AI-Powered Diagnostic Tools on Patient Outcomes in Medical Laboratories</h1>
        <p className="my-4 text-sm font-light max-w-md dark:text-gray-50 line-clamp-2">This study examines the effectiveness of AI-driven diagnostic tools in improving patient outcomes, reducing errors, and enhancing laboratory efficiency. Researchers will analyze data from 100 medical laboratories using AI-powered diagnostic tools and compare results with traditional methods.</p>
        <small className="text-gray-500 dark:text-gray-50">June 10th, 2021</small>
      </div>

      <div className="blog-card flex flex-col items-center md:items-start cursor-pointer">
        <div className="img-container rounded-md overflow-hidden w-3/4 sm:w-1/2 mx-auto md:w-full lg:h-48">
          <img src="https://media.istockphoto.com/id/1465316262/photo/businessman-inspecting-paperwork-document-of-business-data-analysis-working-management-report.webp?b=1&s=170667a&w=0&k=20&c=L6xi5VJG0gr3a40-i35k8XWcmglc5hlgYP-lSqdEd9s=" className="object-cover" alt="headerImage" />
        </div>
        <h1 className="mt-4 text-xl font-semibold dark:text-gray-50">Exploring the Role of Machine Learning in Predicting Disease Progression in Cancer Patients</h1>
        <p className="my-4 text-sm font-light max-w-md dark:text-gray-50 line-clamp-2">This research project utilizes machine learning algorithms to analyze genomic data and predict disease progression in cancer patients. The study aims to identify potential biomarkers and develop personalized treatment plans, improving patient outcomes and quality of life.</p>
        <small className="text-gray-500 dark:text-gray-50">May 17th, 2021</small>
      </div>

      <div className="blog-card flex flex-col items-center md:items-start cursor-pointer">
        <div className="img-container rounded-md overflow-hidden w-3/4 sm:w-1/2 mx-auto md:w-full lg:h-48">
          <img src="https://media.istockphoto.com/id/1465316262/photo/businessman-inspecting-paperwork-document-of-business-data-analysis-working-management-report.webp?b=1&s=170667a&w=0&k=20&c=L6xi5VJG0gr3a40-i35k8XWcmglc5hlgYP-lSqdEd9s=" className="object-cover" alt="headerImage" />
        </div>
        <h1 className="mt-4 text-xl font-semibold dark:text-gray-50">Evaluating the Efficacy of Virtual Reality-Based Training for Medical Laboratory Professionals</h1>
        <p className="my-4 text-sm font-light max-w-md dark:text-gray-50 line-clamp-2">This study assesses the effectiveness of virtual reality (VR)-based training programs for medical laboratory professionals, focusing on skill development, knowledge retention, and error reduction. Researchers will compare VR-based training with traditional methods, measuring participant performance and satisfaction.</p>
        <small className="text-gray-500 dark:text-gray-50">May 17th, 2021</small>
      </div>
    </div>
  </div>
</div>
        <div className="mt-12 flex justify-center">
          <Link className="underline text-xl text-blue-400" href={''} >
            View More
          </Link>
        </div>
      </div>
    </section>
  )
}

function ChevronLeftIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18-6-6 6-6" />
    </svg>
  )
}


function ChevronRightIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}


function XIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
