/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/8krK6PR7Juj
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { AvatarImage } from "@radix-ui/react-avatar";
import { Avatar, AvatarFallback } from "./ui/avatar";
import React, { PureComponent } from 'react';
import {
  ComposedChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  Scatter,
  ResponsiveContainer,
} from 'recharts';
import { Graph } from "./ResearchPattern";

const data = [
  { index: 10000, red: 1643, blue: 790 },
  { index: 1666, red: 182, blue: 42 },
  { index: 625, red: 56, blue: 11 },
  // Calculation of line of best fit is not included in this demo
  { index: 300, redLine: 0 },
  { index: 10000, redLine: 1522 },
  { index: 600, blueLine: 0 },
  { index: 10000, blueLine: 678 },
];

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/


export function ResearchDashboard() {
  return (
    <div className="grid md:grid-cols-2 gap-20 pt-20">
      <div>
        <div className="flex justify-between items-center">
          <h2 className="font-bold text-xl">Project overview</h2>
          <p className="rounded-3xl p-3 bg-white text-xs">This Month</p>
        </div>
        <div className="grid grid-cols-3">
          <div>
            <h3 className="font-bold text-2xl">78</h3>
            <p className="text-sm">Design</p>
          </div>

          <div>
            <h3 className="font-bold text-2xl">78</h3>
            <p className="text-sm">Design</p>
          </div>

          <div className="space-y-2">
            <p className="flex gap-3 items-center">
              <span className="h-3 w-3 bg-blue-200 rounded-full" />
              Design
            </p>

            <p className="flex gap-3 items-center">
              <span className="h-3 w-3 bg-blue-200 rounded-full" />
              Design
            </p>

          </div>
        </div>
        <Graph />
      </div>

      <div className="space-y-5">
        <div className="text-xs flex justify-between items-center">
          <p className="text-xl">
            Recent Activity
          </p>
          <p>View All</p>
        </div>

        <div className="space-y-5">
          <div className="flex items-start gap-10">
            <Avatar>
              <AvatarImage src="" />
              <AvatarFallback>

              </AvatarFallback>
            </Avatar>
            <div className="text-sm space-y-2">
              <h5 className=" text-lg">
                Lorem ipsum dolor sit amet consectetur.
              </h5>
              <p className="text-gray-500">Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum, nulla?</p>
              <div>
                <div>

                </div>
                <p>Lorem, ipsum dolor.<br />12:45 pm</p>
              </div>
            </div>
          </div>

          <div className="flex items-start gap-10">
            <Avatar>
              <AvatarImage src="" />
              <AvatarFallback>

              </AvatarFallback>
            </Avatar>
            <div className="text-sm space-y-2">
              <h5 className=" text-lg">
                Lorem ipsum dolor sit amet consectetur.
              </h5>
              <p className="text-gray-500">Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum, nulla?</p>
              <div>
                <div>

                </div>
                <p>Lorem, ipsum dolor.<br />12:45 pm</p>
              </div>
            </div>
          </div>

          <div className="flex items-start gap-10">
            <Avatar>
              <AvatarImage src="" />
              <AvatarFallback>

              </AvatarFallback>
            </Avatar>
            <div className="text-sm space-y-2">
              <h5 className=" text-lg">
                Lorem ipsum dolor sit amet consectetur.
              </h5>
              <p className="text-gray-500">Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum, nulla?</p>
              <div>
                <div>

                </div>
                <p>Lorem, ipsum dolor.<br />12:45 pm</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      
    </div>
  )
}
