/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/E9ydztxbMtd
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Tenor_Sans } from 'next/font/google'
import { Rubik } from 'next/font/google'

tenor_sans({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { SurveyCollabo } from "./SurveyCollabo"
import { AddQuestionForSurvey } from "./add-question-for-survey"
import { InviteSurvey } from "./invite-survey"
import { SurveyQuestionList } from "./survey-question-list"
import { Graph } from "./ResearchPattern"

//

export function SurveyCreator() {
  return (
    <div className="flex flex-col min-h-screen ">
      <header className=" text-gray-500 py-4 px-6 ">
        <div className=" flex items-center justify-between">
          <h1 className="text-2xl font-bold">Survey Builder</h1>
          <div className="flex items-center gap-4">
            <Link href="#" className="hover:underline" prefetch={false}>
              Home
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              My Surveys
            </Link>
            <Avatar className="h-8 w-8 bg-[#4f46e5] text-white">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
          </div>
        </div>
      </header>
      <main className="flex  ">
        <div className="w-full grid grid-cols-1 md:grid-cols-2 gap-8 m-10">
          <section className="mt-10">
            <h2 className="text-2xl w-full text-center font-bold mb-4 text-[#334155]">Why most people are not successfull</h2>
            <p className="text-center text-gray-500 mb-5">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quaerat ratione ipsam quisquam accusamus aspernatur id veniam deserunt, eaque explicabo magnam.</p>
           <div className="flex justify-center space-x-5">
            {/* <AddQuestionForSurvey /> */}
         

            <button className="px-12 py-4 rounded-full bg-[#1ED760] font-bold text-white tracking-widest uppercase transform hover:scale-105 hover:bg-[#21e065] transition-colors duration-200">
                  Preview Survey
              </button>
           </div>
          </section>
          <section className=" shadow rounded-lg">
            <InviteSurvey />
          </section>
          <section className="w-full col-span-2  rounded-2xl">
            <SurveyQuestionList />
          </section>
         
          <section className=" ">
          <div className="space-y-5">
        <div className="text-xs flex justify-between items-center">
          <p className="text-xl">
            Recent Activity
          </p>
          <p>View All</p>
        </div>

        <div className="space-y-5">
          <div className="flex items-start gap-10">
            <Avatar>
              <AvatarImage src="" />
              <AvatarFallback>

              </AvatarFallback>
            </Avatar>
            <div className="text-sm space-y-2">
              <h5 className=" text-lg">
                Lorem ipsum dolor sit amet consectetur.
              </h5>
              <p className="text-gray-500">Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum, nulla?</p>
              <div>
                <div>

                </div>
                <p>Lorem, ipsum dolor.<br />12:45 pm</p>
              </div>
            </div>
          </div>

          <div className="flex items-start gap-10">
            <Avatar>
              <AvatarImage src="" />
              <AvatarFallback>

              </AvatarFallback>
            </Avatar>
            <div className="text-sm space-y-2">
              <h5 className=" text-lg">
                Lorem ipsum dolor sit amet consectetur.
              </h5>
              <p className="text-gray-500">Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum, nulla?</p>
              <div>
                <div>

                </div>
                <p>Lorem, ipsum dolor.<br />12:45 pm</p>
              </div>
            </div>
          </div>

          <div className="flex items-start gap-10">
            <Avatar>
              <AvatarImage src="" />
              <AvatarFallback>

              </AvatarFallback>
            </Avatar>
            <div className="text-sm space-y-2">
              <h5 className=" text-lg">
                Lorem ipsum dolor sit amet consectetur.
              </h5>
              <p className="text-gray-500">Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum, nulla?</p>
              <div>
                <div>

                </div>
                <p>Lorem, ipsum dolor.<br />12:45 pm</p>
              </div>
            </div>
          </div>
        </div>
      </div>
          </section>
          <div>
            <Graph />
            <div>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet, pariatur cum! Cum ipsa eos odio temporibus rem fugiat non accusantium corrupti repellat modi voluptatibus, neque cupiditate dolorem esse eveniet beatae!</p>
            </div>
          </div>
          
          <section className="col-span-1 md:col-span-2">
            <h2 className="text-2xl font-bold mb-4 text-[#334155]">Preview and Publish</h2>
            <div className=" rounded-lg shadow p-6">
              <div className="mb-4">
                <Label htmlFor="survey-link" className="block font-medium mb-2 text-[#334155]">
                  Survey Link
                </Label>
                <Input
                  id="survey-link"
                  type="text"
                  placeholder="https://example.com/survey"
                  className="w-full  border-[#e2e8f0] focus:ring-[#6366f1] focus:border-[#6366f1]"
                />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <Button variant="outline" className="bg-[#6366f1] text-white hover:bg-[#4f46e5]">
                  <EyeIcon className="mr-2 h-4 w-4" />
                  Preview
                </Button>
                <Button className="bg-[#6366f1] text-white hover:bg-[#4f46e5]">
                  <UploadIcon className="mr-2 h-4 w-4" />
                  Publish
                </Button>
              </div>
            </div>
          </section>
        </div>
        <section className="md:w-[30%]">
            <SurveyCollabo />
          </section>
      </main>
      
    </div>
  )
}

function EyeIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7Z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}


function LayoutTemplateIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="7" x="3" y="3" rx="1" />
      <rect width="9" height="7" x="3" y="14" rx="1" />
      <rect width="5" height="7" x="16" y="14" rx="1" />
    </svg>
  )
}


function PencilIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z" />
      <path d="m15 5 4 4" />
    </svg>
  )
}


function PlusIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function SearchIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function TrashIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>
  )
}


function UploadIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="17 8 12 3 7 8" />
      <line x1="12" x2="12" y1="3" y2="15" />
    </svg>
  )
}


function XIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
