/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/c35wH0sOyRc
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Avatar, AvatarFallback, AvatarImage } from "./ui/avatar"

export function SurveyQuestionList() {
  return (
    <div className="rounded-lg w-full">
      <h2 className="font-bold text-gray-500">Respondents</h2>
      <div className="relative w-full overflow-auto">
        <Table>
          <TableHeader >
            <TableRow>
              <TableHead>Image</TableHead>
              <TableHead>Name</TableHead>
              <TableHead>Questions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody  className="w-full">
            <TableRow>
              <TableCell className="font-medium">
                <Avatar>
                  <AvatarImage className="object-cover" src="https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3534&q=80"  />
                  <AvatarFallback className="src only">
                    avatar
                  </AvatarFallback>
                </Avatar>
              </TableCell>
              <TableCell>Miracle tsaka</TableCell>
              <TableCell>
                <Select>
                  <SelectTrigger className="w-fit text-sm sm:text-base z-50 border-2 border-green-600 dark:text-white bg-transparent text-black h-full rounded-full focus:outline-none focus:ring-0 pl-4 sm:pl-10 pr-20 ">
                    <SelectValue placeholder="Attempted All Questions" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="red">Red</SelectItem>
                    <SelectItem value="green">Green</SelectItem>
                    <SelectItem value="blue">Blue</SelectItem>
                    <SelectItem value="yellow">Yellow</SelectItem>
                  </SelectContent>
                </Select>
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="font-medium">
                <Avatar>
                  <AvatarImage className="object-cover" src="https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3534&q=80"  />
                  <AvatarFallback className="src only">
                    avatar
                  </AvatarFallback>
                </Avatar>
              </TableCell>
              <TableCell>Miracle tsaka</TableCell>
              <TableCell>
                <Select>
                  <SelectTrigger className="w-fit text-sm sm:text-base z-50 border-2 border-green-600 dark:text-white bg-transparent text-black h-full rounded-full focus:outline-none focus:ring-0 pl-4 sm:pl-10 pr-20 ">
                    <SelectValue placeholder="Attempted All Questions" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="red">Red</SelectItem>
                    <SelectItem value="green">Green</SelectItem>
                    <SelectItem value="blue">Blue</SelectItem>
                    <SelectItem value="yellow">Yellow</SelectItem>
                  </SelectContent>
                </Select>
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="font-medium">
                <Avatar>
                  <AvatarImage className="object-cover" src="https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3534&q=80"  />
                  <AvatarFallback className="src only">
                    avatar
                  </AvatarFallback>
                </Avatar>
              </TableCell>
              <TableCell>Miracle tsaka</TableCell>
              <TableCell>
                <Select>
                  <SelectTrigger className="w-fit text-sm sm:text-base z-50 border-2 border-green-600 dark:text-white bg-transparent text-black h-full rounded-full focus:outline-none focus:ring-0 pl-4 sm:pl-10 pr-20 ">
                    <SelectValue placeholder="Attempted All Questions" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="red">Red</SelectItem>
                    <SelectItem value="green">Green</SelectItem>
                    <SelectItem value="blue">Blue</SelectItem>
                    <SelectItem value="yellow">Yellow</SelectItem>
                  </SelectContent>
                </Select>
              </TableCell>
            </TableRow>
           
          </TableBody>
        </Table>
      </div>
    </div>
  )
}
