/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/k8WNTZv24NX
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Chivo } from 'next/font/google'
import { Rubik } from 'next/font/google'

chivo({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Mail } from 'lucide-react'

export function VerifyEmail() {
  return (
    <Card className="w-full max-w-md">
          <CardHeader>
            <CardTitle className="text-2xl text-yellow-400 font-bold text-center">Check Your Email</CardTitle>
            <CardDescription className="text-center">We have sent a verification link to your email address</CardDescription>
          </CardHeader>
          <CardContent className="flex flex-col items-center space-y-4">
            <div className="w-16 h-16 bg-blue-100 rounded-full flex items-center justify-center">
              <Mail className="w-8 h-8 text-blue-600" />
            </div>
            <p className="text-center text-sm text-gray-600">
              Please click on the link in the email to verify your account. If you dont see the email, check your spam folder.
            </p>
            <Link className="flex items-center justify-center gap-2" href="https://accounts.google.com/b/0/AddMailService">
            <Button className="w-full bg-blue-600 hover:bg-blue-700">
              Resend Verification Email
            </Button>
            </Link>
          </CardContent>
        </Card>

  )
}

function MailIcon(props: React.JSX.IntrinsicAttributes & React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  )
}
