import type { Metadata } from "next";
import ResearchNavBar from "@/components/ResearchNavBar";

// const inter = Inter({ subsets: ["latin"] });

//#2a2e7c

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className='bg-[#b6ebec] w-full md:p-6'>
    <div className='bg-white bg-opacity-20 w-full  md:rounded-3xl lg:p-6 border-2 border-white'>
        <div className="w-full">
          <ResearchNavBar />
          {children}
        </div>
      </div>
    </div>
  );
}
