import type { Metadata } from "next";

import { Toaster } from "@/components/ui/sonner";
import ProfileSideBar from "@/components/ProfileSideBar";
import { DashboardNav } from "@/components/dashboard-nav";

// const inter = Inter({ subsets: ["latin"] });

//#2a2e7c

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

      <div >
        <DashboardNav />
        <div className={'flex'}>
        <ProfileSideBar />
        {children}
        </div>
     
      </div>
  );
}
