/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Nj23XOUPrkD
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Practice2 from "@/components/Practice2"
//import { SignupBg } from "@/components/ui/SigninupBg"
import prisma from "@/lib/prisma"
import dynamic from "next/dynamic";
import React from "react"


/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/


const DynamicHeader = dynamic(() => import('@/components/ui/SigninupBg'), {
  ssr: false,
})


export default async function page() {

  const institutions = await prisma.institution.findMany({
    orderBy:{
      createdAt:"desc"
    }
  })

  console.log(institutions)
  return (
      <DynamicHeader>
        <Practice2 institutions={institutions!} />
      </DynamicHeader>
    
  )
}
