/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Nj23XOUPrkD
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { RegisterForm } from "@/components/register-form";
import { ArrowRight, Star } from "lucide-react";
import { InstagramLogoIcon, TwitterLogoIcon } from '@radix-ui/react-icons'
import { Copyright, Facebook } from 'lucide-react'


/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export default function page() {
  return (
      <div className="relative h-screen bg-white w-full">
        <div className="absolute inset-x-0  bottom-0 h-[30rem] bg-[#2a2e7c] -skew-y-12 origin-top-left" />
        <div className="absolute inset-x-0  bottom-0 h-[30rem] bg-[#2a2e7c] origin-bottom-right" />
        <div className="relative max-w-7xl mx-auto z-10 md:grid grid-cols-2 items-center p-6 gap-6">
          <div className="hidden max-w-lg md:flex flex-col gap-4 text-start ">
            <h2 className="font-extrabold">Kuhesmedlab</h2>
            <div className="flex gap-2 ">
                <Star className="h-6 w-6 text-[green]" />
                <div>
                    <h2 className="font-bold mb-2 text-gray-700">Get started quickly</h2>
                    <p className="text-xs text-gray-400">Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo corrupti cumque odio voluptatum explicabo eaque mollitia,
                     repellendus similique iste eos eveniet repudiandae culpa optio aspernatur quas, qui doloribus voluptate sed..</p>
                </div>
            </div>
            <div className="flex gap-2 items-start">
                <Star className="h-6 w-6 text-[green]" />
                <div>
                    <h2 className="font-bold mb-2 text-gray-700">Get started quickly</h2>
                    <p className="text-xs text-gray-400">Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo corrupti cumque odio voluptatum explicabo eaque mollitia,
                     repellendus similique iste eos eveniet repudiandae culpa optio aspernatur quas, qui doloribus voluptate sed..</p>
                </div>
            </div>
            <div className="flex gap-2 items-start">
                <Star className="h-6 w-6 text-[green]" />
                <div>
                    <h2 className="font-bold mb-2 text-gray-700">Get started quickly</h2>
                    <p className="text-xs text-gray-400">Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo corrupti cumque odio voluptatum explicabo eaque mollitia,
                     repellendus similique iste eos eveniet repudiandae culpa optio aspernatur quas, qui doloribus voluptate sed..</p>
                </div>
            </div>
          </div>
          <RegisterForm />
          <div className='flex justify-between items-center pt-5'>
            <div className='flex gap-5 items-center'>
                <Facebook className='h-4 w-4 text-white' />
                <InstagramLogoIcon className='h-4 w-4 text-white' />
                <TwitterLogoIcon className='h-4 w-4 text-white' />
            </div>
            <p className='text-xs text-white flex items-center'><Copyright className='h-4 w-4 font-extralight' /> Kuhesmedlab</p>
        </div>
        </div>
      </div>
    
  )
}
