import type { Metadata } from "next";

import SurveySIdeBar from "@/components/SurveySIdeBar";
import ResearchSideBar from "@/components/ResearchSideBar";

// const inter = Inter({ subsets: ["latin"] });

//#2a2e7c

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <div className='bg-[#b6ebec] p-6'>
    <div className='bg-white bg-opacity-20  rounded-3xl p-6 border-2 border-white'>
      <div className='flex bg-white bg-opacity-40  rounded-3xl  space-y-5'>
        <ResearchSideBar />
        {children}
        </div>
      </div>
    </div>
  );
}
